server:
  port: 7777
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
spring:
  application:
    name: usk-gateway
  cloud:
    gateway:
      routes:
      - id: order
        uri: lb://order-service
          #http://localhost:8082/
        predicates:
        - Path=/order/**
      - id: user
        uri: lb://user-service
          #http://localhost:8081/
        predicates:
        - Path=/user/**
          
